version: "3.9"
services:
  synpress:
    container_name: synpress
    build:
      dockerfile: ./Dockerfile.e2e
      context: .
      args:
        - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
        - WALLETCONNECT_PROJECT_ID=${WALLETCONNECT_PROJECT_ID}
        - FATHOM_SITE_ID=${FATHOM_SITE_ID}
        - FATHOM_API_KEY=${FATHOM_API_KEY}
    env_file: .env.synpress
    environment:
      - DISPLAY=display:0.0
    depends_on:
      - display
      - video
    entrypoint: []
    working_dir: /app
    volumes:
      - ./docker/videos:/app/public-report/screenshots
      - ./docker/screenshots:/app/public-report/videos
    command: yarn test:e2e
    networks:
      - x11

  display:
    container_name: display
    image: synthetixio/display:b2643097e891906524e52e7ee956260b20fa01fb-base
    environment:
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11

  ngrok:
    profiles:
      - ngrok
    container_name: ngrok
    image: synthetixio/ngrok:b2643097e891906524e52e7ee956260b20fa01fb-base
    ports:
      - "4040:4040"
    command: ["ngrok", "http", "display:8080", "--authtoken", "${NGROK_AUTH}"]
    depends_on:
      - display
    networks:
      - x11

  video:
    container_name: video
    image: synthetixio/video:b2643097e891906524e52e7ee956260b20fa01fb-base
    volumes:
      - ./docker/videos-ci:/videos
    environment:
      - FILE_NAME=CI-full-video.mp4
    depends_on:
      - display
    networks:
      - x11

networks:
  x11:
