version: "3.9"
services:
  synpress:
    container_name: synpress
    build:
      dockerfile: ./Dockerfile.e2e
      context: .
      args:
        - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
        - WALLETCONNECT_PROJECT_ID=${WALLETCONNECT_PROJECT_ID}
        - FATHOM_SITE_ID=${FATHOM_SITE_ID}
        - FATHOM_API_KEY=${FATHOM_API_KEY}
    depends_on:
      - display
      - video
    entrypoint: []
    working_dir: /app
    volumes:
      - ./docker/videos:/app/public-report/screenshots
      - ./docker/screenshots:/app/public-report/videos
    environment:
      - DISPLAY=display:0.0
    command: >
      bash -c 'yarn wait-on http://display:8080 && yarn test:e2e:ci'
    networks:
      - x11

  display:
    container_name: display
    image: synthetixio/display:b2643097e891906524e52e7ee956260b20fa01fb-base
    environment:
      - RUN_XTERM=no
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
    ports:
      - "8080:8080"
    networks:
      - x11

  video:
    container_name: video
    image: synthetixio/video:b2643097e891906524e52e7ee956260b20fa01fb-base
    volumes:
      - ./docker/videos-ci:/videos
    environment:
      - FILE_NAME=CI-full-video.mp4
    depends_on:
      - display
    networks:
      - x11

networks:
  x11:
