version: "3.9"
services:
  synpress:
    profiles:
      - synpress
    container_name: synpress
    build: ./packages/frontend
    environment:
      - SKIP_METAMASK_SETUP=true
      - NETWORK_NAME=sepolia
      - DISPLAY=display:0.0
      - CYPRESS_DOCKER_RUN=true
      - CI=true
      - SYNDEBUG=true
      - IS_TESTNET=true
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
      - WALLETCONNECT_PROJECT_ID=${WALLETCONNECT_PROJECT_ID}
      - FATHOM_SITE_ID=${FATHOM_SITE_ID}
      - FATHOM_API_KEY=${FATHOM_API_KEY}
    entrypoint: []
    working_dir: /app
    command: >
      yarn test:e2e
    depends_on:
      - display
      - video
    networks:
      - x11

  display:
    profiles:
      - synpress
    container_name: display
    image: synthetixio/display:016121eafdfff448414894d0ca5a50b1d72b62eb-base
    environment:
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11

  video:
    profiles:
      - synpress
    container_name: video
    image: synthetixio/video:457bb48776c3b14de232d9dda620ba9188dc40ac-base
    volumes:
      - ./docker/videos-ci:/videos
    environment:
      - FILE_NAME=CI-full-video.mp4
    depends_on:
      - display
    networks:
      - x11

networks:
  x11:
