version: "3.9"
services:
  synpress:
    profiles:
      - synpress
    container_name: synpress
    build: ./packages/frontend
    environment:
      - SKIP_METAMASK_SETUP=true
      - DISPLAY=display:0.0
      - CYPRESS_DOCKER_RUN=true
      - CI=true
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
      - WALLETCONNECT_PROJECT_ID=${WALLETCONNECT_PROJECT_ID}
      - FATHOM_SITE_ID=${FATHOM_SITE_ID}
      - FATHOM_API_KEY=${FATHOM_API_KEY}
    entrypoint: []
    working_dir: /app
    command: >
      yarn test:e2e
    depends_on:
      - display
    networks:
      - x11

  display:
    profiles:
      - synpress
    container_name: display
    image: synthetixio/display:016121eafdfff448414894d0ca5a50b1d72b62eb-base
    environment:
      - RUN_XTERM=no
      - DISPLAY_WIDTH=800
      - DISPLAY_HEIGHT=600
    ports:
      - "8080:8080"
    networks:
      - x11

networks:
  x11:
