[package]
name = "ipfs-pinner"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "1.0.2", features = ["ws", "rustls"] }
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }
eyre = "0.6.8"
lazy_static = "1.4.0"

# Telemetry
yansi = "0.5.1"
ansi_term = "0.12.1"
tracing = "0.1.36"
tracing-bunyan-formatter = "0.3.4"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["fmt", "env-filter", "ansi"] }
chrono = "0.4.22"

[build-dependencies]
ethers = { version = "1.0.2", features = ["abigen"] }
eyre = "0.6.8"