name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true
  INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
  WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID }}
  FATHOM_SITE_ID: ${{ secrets.FATHOM_SITE_ID }}
  FATHOM_API_KEY: ${{ secrets.FATHOM_API_KEY }}
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Test e2e
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./packages/frontend
          start: yarn start:staging 
      - name: Build
        run: yarn build
      - name: Size check
        run: yarn size-limit
