name: CI
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main
  schedule:
    - cron: "0 0 * * *"
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
  WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID }}
  FATHOM_SITE_ID: ${{ secrets.FATHOM_SITE_ID }}
  FATHOM_API_KEY: ${{ secrets.FATHOM_API_KEY }}
  HUSKY: "0"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable --prefer-offline
      - name: Run linter
        run: yarn lint
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable --prefer-offline
      - name: Run tests
        run: yarn test
  size-limit:
    name: Size limit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable --prefer-offline
      - name: Check size limit
        run: yarn size-limit
  e2e-test:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: setup-buildx
      - name: Build testable host frontend image
        run: docker-compose -f docker-compose.e2e.yml --env-file .env.e2e up --build --exit-code-from synpress
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
