name: E2E (cypress-action)
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label ||
    github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: actions/cache@v3
        with:
          path: /root/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/node_modules/cypress/package.json') }}
      - run: |
          yarn cypress install
          yarn cypress info
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - uses: actions/cache/restore@v3
        with:
          path: cache
          key: ${{ runner.os }}-hardhat-${{ hashFiles('hardhat.config.js') }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-hardhat-${{ hashFiles('hardhat.config.js') }}-
      - uses: cypress-io/github-action@v4
        with:
          install: false
          record: true
          parallel: true
          start: yarn start:staging
          wait-on: "http://localhost:3000"
          browser: electron
          group: e2e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title || github.event.head_commit.message }}
          COMMIT_INFO_AUTHOR: ${{ github.event.sender.login || github.event.head_commit.author.login }}
