name: E2E (cypress-action)
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label ||
    github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: actions/cache@v3
        with:
          path: /root/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/node_modules/cypress/package.json') }}
      - run: |
          yarn cypress install
          yarn cypress info
      - uses: actions/cache/restore@v3
        with:
          path: cache
          key: ${{ runner.os }}-hardhat-${{ hashFiles('hardhat.config.js') }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-hardhat-${{ hashFiles('hardhat.config.js') }}-
      - uses: cypress-io/github-action@v4
        with:
          install: false
          record: true
          parallel: true
          start: yarn start:staging
          wait-on: "http://localhost:3000"
          browser: electron
          group: e2e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID }}
          FATHOM_SITE_ID: ${{ secrets.FATHOM_SITE_ID }}
          FATHOM_API_KEY: ${{ secrets.FATHOM_API_KEY }}
